Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.network "forwarded_port", guest: 80, host: 8095
# config.vm.provision "shell", path: "script.sh"
# config.vm.synced_folder "site", "/var/www/html"
# config.vm.network "public_network"
  config.vm.network "public_network", ip: "192.168.1.30"
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.name = "desafio-02"
  
  end
  
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../ansible/playbook.yml"
   end

end
