Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"
  config.vm.network "forwarded_port", guest: 80, host: 8090
  config.vm.provision "shell", path: "script.sh"
# config.vm.synced_folder "site", "/var/www/html"
  config.vm.network "public_network"
# config.vm.network "public_network", ip: "192.168.1.55"
  
  config.vm.provider :virtualbox do |vb|
    vb.name = "desafio-01"
  end
end
